- .gitignore
- config.toml
- site.yml
@zregvart this should automatically add the Camel K section built from the `antora` branch.
> Add Camel K to staging website

- .gitignore
- Jenkinsfile
- antora-ui-camel/package.json
- package.json
Reverts apache/camel-website#5
> Revert "CAMEL-11500: PnP and better cache usage"

- antora-ui-camel/src/css/responsive.css
- content/docs/building.md
- content/docs/getting-started.md
- content/docs/sources.md
- content/download/_index.md
- layouts/docs/single.html
- layouts/download/download.html
- layouts/shortcodes/bootstrap-table.html
Add a Hugo shortcode for table template design.
Add pages for:
- getting-started
- sources
- building
- download
> [CAMEL-12998] Add a table shortcode, getting-started and download pages

- Jenkinsfile
Adds preview GitHub status to pull requests, served from Jenkins
workspace.
> feat: preview on pull requests

- config.toml
- layouts/partials/footer.html
@zregvart I add the books menu item now just not to forget ;)
> [CAMEL-12998] - Add a books menu item

- .yarnrc
- yarn.lock
[warning: current version of Yarn is out of date. [CAMEL-13343]](https://issues.apache.org/jira/browse/CAMEL-13343?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16796579#comment-16796579)
fixed
> changed .yarnrc and add the new yarn version to .yarn/releases/ CAMEL-13343

- .yarnrc
- antora-ui-camel/.yarnrc
- yarn.lock
[warning: current version of Yarn is out of date. [CAMEL-13343]](https://issues.apache.org/jira/browse/CAMEL-13343?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=16796579#comment-16796579)
fixed.
>  changed antora-ui-camel/.yarnrc and add the new yarn version to antora-ui-camel/.yarn/releases/

- antora-ui-camel/yarn.lock
- package.json
- yarn.lock
Upgrades dependencies and makes use of semantic versioning version selection (`~ver`) in `package.json`.
> chore: upgrade dependencies

- archetypes/news-entry.md
- content/news/RELEASE-2.24.0.md
- content/news/_index.md
- layouts/news-entry/single.html
- layouts/news/list.html
- layouts/news/news.html
This is a proposal, any feedback are welcome.
> [CAMEL-13567] Create archetype for blog/news section of the site

- content/community/articles.md
- content/community/books.md
- content/community/support.md
- content/docs/building.md
- content/docs/getting-started.md
- content/docs/sources.md
- content/download/_index.md
- layouts/index.html
- layouts/partials/footer.html
Hi, here I just fixed all the missing slashes. Next step is to fix .adoc files
> 16 errors fixed 11 error logs reduced

- content/community/articles.md
- content/community/support.md
Sorry for not being active in this week, My new semester began since I could`t do much. Hopefully do better in this weekend
> fixes for page not found errors

- .gitignore
- content/community/support.md
- layouts/partials/footer.html
I`m not sure whether this is the correct way of adding microdata. Please let know. And if this data okay, Ill find a way to incorporate them antora camel themes  as well
> added microdata to hugo footer.html

- antora-ui-camel/src/partials/footer-content.hbs
I added camel hugo footer into antora camel theme footer
> antora footer edited

- antora-ui-camel/src/partials/footer-content.hbs
- antora-ui-camel/src/partials/footer-scripts.hbs
- layouts/partials/footer.html
- static/robots.txt
I added a twitter account link and a little description about the camel from google search. please let me know if there any correction needed.
> microdata added about twitter account and few more additional details

- README.md
- config.toml
- content/projects/camel-quarkus.md
- site.yml
Please merge after https://github.com/apache/camel-quarkus/pull/105
> CAMEL-13805: Add Camel Quarkus page

- antora-ui-camel/src/partials/footer-content.hbs
- config.toml
- content/_index.md
- content/community/support.md
- layouts/partials/footer.html
Point to Contributing page instead of CONTRIBUTING.md on GitHub.
PS My editor automatically removes unnecessary spaces at the end of paragraphs.
> CAMEL-14061 camel-website - Add page for contributing

- static/schema/cxf/camel-cxf-3.0.0-RC1-blueprint.xsd
- static/schema/cxf/camel-cxf-3.0.0-RC1-spring.xsd
- static/schema/cxf/camel-cxf-3.0.0-RC2-blueprint.xsd
- static/schema/cxf/camel-cxf-3.0.0-RC2-spring.xsd
- static/schema/cxf/camel-cxf-3.0.0-RC3-blueprint.xsd
- static/schema/cxf/camel-cxf-3.0.0-RC3-spring.xsd
- static/schema/cxf/camel-cxf-3.0.0-blueprint.xsd
- static/schema/cxf/camel-cxf-3.0.0-spring.xsd
> Added missing CXF xsds

- static/schema/spring-security/camel-spring-security-3.0.0-RC1.xsd
- static/schema/spring-security/camel-spring-security-3.0.0-RC2.xsd
- static/schema/spring-security/camel-spring-security-3.0.0-RC3.xsd
- static/schema/spring-security/camel-spring-security-3.0.0.xsd
> Added missing xsds for camel-spring-security

- static/schema/blueprint/camel-blueprint-3.0.0-RC1.xsd
- static/schema/blueprint/camel-blueprint-3.0.0-RC2.xsd
- static/schema/blueprint/camel-blueprint-3.0.0-RC3.xsd
- static/schema/blueprint/camel-blueprint-3.0.0.xsd
@zregvart @davsclaus 
I added the xsd taken from camel-blueprint jars on maven central and by renaming it. I think this is what we were doing through svn more or less.
> Added missing camel-blueprint xsd after 3.0.0 release

- static/schema/spring/camel-spring-3.0.0-RC1.xsd
- static/schema/spring/camel-spring-3.0.0-RC2.xsd
- static/schema/spring/camel-spring-3.0.0-RC3.xsd
- static/schema/spring/camel-spring-3.0.0.xsd
> Added missing xsds for camel-spring

- content/blog/Camel3-Whatsnew/index.md
> fix(typo): camel-bean

- antora-ui-camel/src/css/frontpage.css
- layouts/index.html
This replaces the catchphrase "Integration you want" with "Camel 3.0 is
here, what's new" and links the "what's new" to the Camel 3 changes blog
post.
> chore: new catchphrase for Camel 3 announcement

- static/.htaccess
I don't know how to test if the config is correct. it is working without the configuration locally but not on the live website
> Allow to embed youtube videos

- content/blog/capi-gateway/index.md
I've run a spell/grammar checker and fixed formatting.
@rodrigoserracoelho can you have a look?
> refactor: spelling, grammar, and formatting

- config.toml
- content/projects/camel-kafka-connector.md
> Add camel-kafka-connector to projects list

- content/blog/Camel3-Whatsnew/index.md
I'm not sure with the English on all changes so please advice in case I went wrong with some of these.
> Update index.md with typo fixes

- .gitignore
- Jenkinsfile
- antora-ui-camel/src/css/doc.css
- antora-ui-camel/src/css/release.css
- antora-ui-camel/src/css/site.css
- content/blog/RELEASE-2.23.4/index.md
- content/blog/RELEASE-2.24.0/index.md
- content/blog/RELEASE-2.24.2/index.md
- content/blog/RELEASE-2.24.3/index.md
- content/blog/RELEASE-2.25.0/index.md
- content/blog/RELEASE-3.0.0-RC1/index.md
- content/blog/RELEASE-3.0.0-RC2/index.md
- content/blog/RELEASE-3.0.0-RC3/index.md
- content/blog/RELEASE-3.0.0/index.md
- content/blog/RELEASE-3.0.1/index.md
- content/blog/RELEASE-3.1.0/index.md
- content/releases/_index.md
- content/releases/release-3.0.0-RC1.md
- content/releases/release-3.0.0-RC2.md
- content/releases/release-3.0.0-RC3.md
- content/releases/release-3.1.0.md
- layouts/release-note/single.html
- layouts/releases/list.html
- package.json
This adds the data from ASF JIRA to the releases layout and reformats
the releases page.
> CAMEL-12470: publish release notes

- content/blog/2019-Numbers/index.md
- content/blog/ApacheConNA-2020-CFP/index.md
- content/blog/Camel-Kafka-connector-intro/index.md
- content/blog/Camel3-2monthsaway/index.md
- content/blog/Camel3-Whatsnew/index.md
- content/community/books.md
I have reviewed the documents and found some grammatical errors and typos. So I have fixed them :)
> Grammar fix

- layouts/index.html
"what's new" seemed a little ambiguous to me, I think "What's new? " is looks better in its place. 
P.S - this is my first ever pull request. just happy to even make it.
> Changed "what's new" to "What's new?

- README.md
A step by step guide added to install nvm on the system for the ease of users and revert back to `nvm alias default 10`.
> Update README to include installation guide on nvm 

- content/blog/Camel3-Whatsnew/index.md
Index.md file was using table structure with inconsistent strong properties. That was making the page less attractive.
I have replaced the table structure with the unordered list and removed the inconsistency.
> Replace table with unordered list

- antora-ui-camel/src/css/blog.css
Added styling to the table by making the table header to have the camel orange background color and made the table to be striped as shown on the screen shot
> Made table style to be stripped and added padding

- antora-ui-camel/src/css/doc.css
- antora-ui-camel/src/css/header.css
- Search results push the website's Navbar.
- Searched result div should be scrollable.
- I have fixed the overlapping issue of the navbar items and searched result fiv. I have also added scrollbar to searched result div.
> Searched result styling

- antora-ui-camel/src/css/frontpage.css
This PR will solve the issue [CAMEL-14676](https://issues.apache.org/jira/browse/CAMEL-14676)
I have updated the `frontpage.css` with new values of animation-delay and stroke-opacity.
Please review the changes made via this PR.
> updated the stroke-opacity and animation delay for more apparent swoosh animation.

- antora-ui-camel/src/css/blog.css
- config.toml
Styled tables appearing in Blogs for Apache Camel Website
In response to Issue 14674 : https://issues.apache.org/jira/browse/CAMEL-14674
- added bottom margin for table
- added odd-even distinction for table rows
- added padding for table cells
- added different colour and more padding to table headers
- centre-aligned the table and text in the table
- widened the table to align with the content written around it
> CAMEL-14674: Nicer table design for the blog post

- antora-ui-camel/src/css/header.css
Regarding the issue i created on jira
CAMEL-14688
____ EARLIER ___
__NOW__
> Search bar overlapping issue fixes

- antora-ui-camel/src/css/header.css
- antora-ui-camel/src/partials/header-content.hbs
- layouts/partials/header.html
Fixes: https://issues.apache.org/jira/browse/CAMEL-14695?filter=12348381
> Mobile Menu Enhancement

- README.md
* A step by step installation guide for windows users to install yarn and nvm using chocolatey.
* Instructions to install chocolatey is also provided.
* All further steps to build and install are the same on all OS systems.
> CAMEL-14696: Document working on the website on Windows 

- content/blog/Camel3-Whatsnew/index.md
after change 
Just added a line there.
> minor changes in under camel-whatsnew

- antora-ui-camel/src/css/nav.css
- layouts/partials/header.html
I have removed the unused HTML from the header. It was not visible to users because of the styling and was of no use.
> Removed unused html from header

- antora-ui-camel/src/css/header.css
I have fixed the vertical alignment of the navbar items as those items were not aligned before.
> Vertical alignment of navbar items

- antora-playbook.yml
- config.toml
- content/_index.md
playbook and front page changes for aggregated eip content as a module under the components component.
> resolves task 14758 Issue 14747 aggregate eip into components module

- static/.htaccess
I wrote something to generate these changes, and they look good to me, but I'm not sure how to test them.
> resolves camel-14768: fix .htaccess targets

- package.json
- Since, menu.js file was deleted, the preview was not working. 
I made the required changes and checked it. Now my preview is working.
> Made required changes in package.json to be able to preview the website

- antora-ui-camel/src/css/frontpage.css
In this PR added equal padding to each section in frontpage
> chore: equal space in each frontpage section

- antora-playbook.yml
This should have been an issue associated with CAMEL-14765 and CAMEL-14766 but I forgot.
> Resolves CAMEL-14783: task of CAMEL-14782: add new start_paths to playbook

- content/community/team.md
There are some alignment issues on the team page. Markdown file has some spacing issues which I have removed and fixed the alignment issues. I have attached the screenshots below, changes can be seen there.
> Fixed alignment issue

- antora-ui-camel/src/css/header.css
- antora-ui-camel/src/js/04-mobile-navbar.js
- Added drop-downs for menu items having sub-menus, so that all main-menu items are visible in first glance. 
- Made menu full length and adjusted width
- Fixed padding issues
> CAMEL-14695: Improve Mobile Main-Menu

- antora-ui-camel/src/css/frontpage.css
This PR is related to PR #202 
I changed dark colors in Swoosh animation with lighter shades to increase the visibility of text.
> swoosh animation updated

- static/schema/HEADER.html
- static/schema/spring/HEADER.html
This adds a fix for Viewport not set (3 pages) from [Mobile usability issues reported in Google search console](https://issues.apache.org/jira/browse/CAMEL-13800)
I have added Viewport in [HEADER.html pages under static/schema](https://issues.apache.org/jira/browse/CAMEL-13800?focusedCommentId=17064648&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17064648)
cc: @zregvart
> chore: add viewport to HEADER.html files

- README.md
- netlify.toml
We need to attribute Netlify, hopefully adding attribution to the README
would suffice.
> chore: configure Netlify

- antora-ui-camel/src/css/blog.css
- antora-ui-camel/src/css/doc.css
- antora-ui-camel/src/css/frontpage.css
- content/blog/LTS-Release-Schedule/index.md
- layouts/blog/post.html
- layouts/download/download.html
- layouts/shortcodes/table.html
* The purpose of the PR is to create all the pages within the website responsive irrespective of the screen width.
* It was observed that certain webpages under smaller screen width, the entire webpage doesn't fit the screen and the user needs to scroll through the screen to access the navbar. It is observed in several webpages.
* Currently, I have resolved this issue for
1. Downloads page
2. Projects section all page
3. Blog page and all the articles within it
4. Front-page
5. Community page
6. User manual pages
7. EIP
8. Migration and upgrade guide
> CAMEL-14745: make changes to create a  responsive mobile design

- antora-ui-camel/src/css/vars.css
- content/community/team.md
- content/community/user-stories.md
* The table alignment was improper within the team page. Hence, in the **team.md**, I wrote the table in a structure and neat manner and it solves the alignment issue for the table within the **Teams** page.
> fix table alignment issue within Team page

- antora-ui-camel/src/css/blog.css
- antora-ui-camel/src/css/highlight.css
- antora-ui-camel/src/css/pagination.css
- antora-ui-camel/src/css/vars.css
* After running audit, it was observed that the accessibility factor under the blog section was decreasing due to various factors, one of them including the **color contrast**. 
* For the case of  **color contrast**, I have made all required changes to get the right **COLOR CONTRAST RATIO** while keeping in mind the aesthetic and presentability of the pages under the blog section.
> CAMEL-14581: improve accessibility ratio through color contrast under blog section

- antora-ui-camel/src/css/frontpage.css
This PR is related to #264 . I suppose right alignment of heading looks more appropriate.
> changed alignment of headings under project section

- antora-ui-camel/src/css/doc.css
- antora-ui-camel/src/css/release.css
In this PR, I have changed the design of all table that is present on the website. I have changed the design to make UI same for all the tables.
**Before:**
**After:**
Release table:-
**Before:**
**After:**
> Table new design

- antora-ui-camel/src/css/footer.css
- antora-ui-camel/src/partials/footer-content.hbs
- layouts/partials/footer.html
- package.json
Based on #301 this adds "Back to top" link above the footer. @psingh587 can you have a look?
> chore: add back to top link

- antora-ui-camel/src/css/header.css
* I had some issues regarding the arrangement with the text within the **navbar** and in the **header frontpage**.
1.  In the **navbar**, the navbar links were really close to the logo brand, hence I provided a margin between the logo and the **navbar-end**.
> Improvize the frontpage design

- antora-ui-camel/src/css/release.css
> made 'release 2.21.2' page responsive

- antora-ui-camel/src/css/header.css
With the recent changes, the search-cancel button had got disoriented. I made changes to fix it.
> Search-Cancel Button position fixes in the search box

- antora-playbook-xrefcheck.yml
- package.json
> Fixes CAMEL-14896: set up to build using indexer

- antora-ui-camel/src/partials/footer-content.hbs
- antora-ui-camel/src/partials/header-content.hbs
- config.toml
- layouts/partials/footer.html
- layouts/partials/header.html
Fixes: https://issues.apache.org/jira/browse/CAMEL-13888
> CAMEL-13888: Add rel tag to external links

- package.json
- yarn.lock
This is the camel-website change for the issue.
> For CAMEL-15182: bump indexer version to support dlists

- antora-playbook.yml
Reverts apache/camel-website#402
> Revert "Add camel-kafka-connector-0.3.x branch to antora"

- antora-ui-camel/src/css/nav.css
- antora-ui-camel/src/css/vars.css
This introduces the scrollbar design for the nav menu panel under the documentation section after the rebasing in PR #383 altered the change in design. I change the contrast color with respect to the basic contrast ratio for scrollbars.
> CAMEL-15202: Add the custom scrollbar for nav menu panel

- antora-ui-camel/src/css/blog.css
- antora-ui-camel/src/css/nav.css
- layouts/_default/taxonomy.html
- layouts/blog/list.html
> fix: adjustments for the category box within blog section

- antora-ui-camel/src/css/blog.css
- antora-ui-camel/src/css/docs.css
In this PR, I decided to cover fixing two bugs I found on the website to create a better responsive website. These are small changes however it resolves the following issues stated.
1. The blog posts are unresponsive to the website. You can observe this error at 1024px and more for each blog post.
2. Due to the height defined to 10rem on the description of the project in the docs page, there tends to be a clustering between the links and the description.
> fix: unresponsiveness related bugs on the website.

- antora-ui-camel/src/css/doc.css
> fix: image and link presentation within eip table

- antora-ui-camel/src/css/footer.css
- antora-ui-camel/src/css/vars.css
- antora-ui-camel/src/img/hide-footer-menu.svg
- antora-ui-camel/src/img/show-footer-menu.svg
- antora-ui-camel/src/partials/footer-content.hbs
- layouts/partials/footer.html
Reverts apache/camel-website#428
> Revert "CAMEL-15185: Footer design"

- antora-ui-camel/src/css/fa-emulated.css
- antora-ui-camel/src/css/site.css
Motivated by https://github.com/apache/camel-quarkus/issues/1410 , based on https://gitlab.com/antora/antora-ui-default/-/merge_requests/121/diffs
> Emulate the parts of FontAwesome that we use

- antora-ui-camel/src/css/blog.css
- antora-ui-camel/src/css/category.css
- antora-ui-camel/src/css/docs.css
- antora-ui-camel/src/css/frontpage.css
> fix: remove underline for logos

- content/blog/2020/09/windup/index.md
> Blog post: Upgrading to Camel 3 with Windup

- content/blog/2020/09/Camel35-Whatsnew/index.md
> Fix typo configuers --> configurers

- content/blog/2020/09/Camel35-Whatsnew/index.md
> Fix property/attribute name country --> country

- content/blog/2020/09/Camel35-Whatsnew/index.md
not sure about this one but the Map<Country> doesn't sound possible
> Fix Map generic types for @Configurer

- content/blog/2020/10/camel-k-release-1.2.0/index.md
Add a short blog post to announce the release
> Camel k 1.2.0 released

- README.md
it allows to spot more easily where the build is happening
> Add badge for CI

- content/community/user-stories.md
Hi community
I've developed a Component to integrate with Apache RocketMQ and used it in my own projects.
Now I want to share it with community.
> Add a new external Camel Component to User Stories

- .github/workflows/pr.yaml
- .github/workflows/preview.yaml
Try not to rely on `pull_request_target` event, instead refactor into
two workflows triggered by `pull_request` and `workflow_run` events.
> chore(github): refactor GitHub workflow

- antora-ui-camel/src/css/sharingbuttons.css
- antora-ui-camel/src/css/site.css
- layouts/blog/post.html
Let's add Twitter share button to each blog post, so that we can share great articles more easily ;-)
> feat(blog): add Twitter share button to blog post

- static/.htaccess
Needed after Camel Kafka Connector doc reorganization.
> Added redirect for camel-kafka-connector connector list page.

- content/blog/2021/07/camel-k-properties-refactoring/index.md
> fix: blog links

- content/community/user-stories.md
Based on recent ApacheCon presentation of ROMA - https://apachecon.com/acasia2021/sessions/1075.html
> Mentioning Huawei Cloud ROMA as Camel's success story

- content/blog/2021/09/camel-k-release-1-6/index.md
Short blog post announcing Camel K 1.6 release.
> feat(camel-k): 1.6 release blog post

- content/releases/q/release-2.4.0.md
> Add camel-quarkus 2.4.0 release so its updated on download page.

- content/blog/2021/11/camel-k-release-1-7/index.md
Please @oscerd @nicolaferraro @astefanutti @phantomjinx @claudio4j @tadayosi  have a look to confirm the high level description of the new features introduced is okey or we need to add something else.
> feat: camel k 1.7 announcement

- content/blog/2021/11/camel-k-release-1-7/index.md
Will fix https://github.com/apache/camel-k/pull/2781#issuecomment-979245051
> fix: camel k navigation link structure change

- antora-playbook.yml
> :memo: Add documentation for Camel Quarkus 2.5.x

- content/releases/kamelets/release-0.3.0.md
- content/releases/kamelets/release-0.4.0.md
- content/releases/kamelets/release-0.5.0.md
- data/release-categories.yaml
- layouts/partials/releases/camel-kamelets.html
> chore: add releases for Kamelets subproject

- content/blog/2021/12/vscode-releases/index.md
> provide release announcement for VS Code extensions

- content/blog/2021/12/vscode-releases/index.md
> Fix layout of last blogpost article

- antora-playbook.yml
- playbook-patch-full.yml
I left in some compatibility for the first version of local builds, which can now be removed.
> Completes #731, #720: remove compatibility for first version of local builds, now gone

- content/blog/2022/01/dynamic-router-eip-component/index.md
I messed up the external image link syntax, and fixed it in this merge request.
> CAMEL-17154: Fixed Dynamic Router EIP image link.

- content/releases/k-runtime/release-1.11.0.md
- content/releases/k/release-1.8.0.md
- content/releases/kamelets/release-0.7.0.md
Camel-K 1.8.0 release with
camel-k-runtime 1.11.0 release and camel-kamelets 0.7.0 release
> Camel k 1.8.0 and friends

- layouts/partials/header.html
> fix: social link dynamically retrieved

- content/blog/2021/07/camel-k-release-1-5/index.md
See https://github.com/apache/camel-k/issues/2898
> preview of AsciiDoc crd API docs. Adjust blog link to new page name.

- antora-playbook-snippets/antora-playbook.yml
Preview should work against actual branch...
> camel quarkus 2.7.x doc branch, with preview

- Jenkinsfile
- static/.asf.yaml
I think these "code" changes are what's needed to publish to a separate repo `camel-website-pub.git`.
See issue for additional steps.
> Resolves issue #733: modifications to publish to separate git repo

- content/blog/2022/02/camel-textual-debug-eclipse-vscode/index.md
> Fix list rendering in blogpost on textual debugger in VS code and

- antora-ui-camel/src/img/karavan.svg
- content/_index.md
- content/docs/_index.md
Initial information about Apache Camel Karavan project
> Initial Apache Camel Karavan Information

- content/blog/2022/04/start-camel-application-with-camel-textual-debug-in-vscode/index.md
VS Code in a single action
Video mentioned to be created, published and link to be provided in the blogpost.
Planned for tomorrow
> Blogpost how to start Camel application with Camel Textual Debugger in

- config.toml
- content/misc/security.md
- layouts/security/single.txt
- static/.well-known/dnt/.htaccess
- static/.well-known/dnt/index.dnt
[chore: add tracking DNT resource](https://github.com/apache/camel-website/commit/1aaac8ac43788ea9ba4155818bcc9288d11f7247)
In accordance with https://www.w3.org/TR/tracking-dnt/.
[chore: add RFC8615 security content](https://github.com/apache/camel-website/commit/ea034104deb0c18a68178aac0d5cd3ff8b6df534)
In accordance with https://www.rfc-editor.org/rfc/rfc9116.
> Adds various RFC8615 data

- content/blog/2022/05/vscode-extensions-release-language-0.3.0/index.md
> Blogpost for new release of VS Code language support for camel 0.3.0

- content/blog/2022/05/start-camel-quarkus-application-with-camel-textual-debug-in-vscode/index.md
Camel routes in VS Code with a single launch configuration
> Blogpost How to start a Camel Quarkus application with Textual debug for

- content/community/team.md
Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
Adding my name as a contributor, as I have contributed to code fixes.
> Adding name to contributor table

- content/blog/2022/06/HowToUseCamelRouteTextualDebuggerWithUnitTest/index.md
> Fix path to file in blogpost

- content/releases/release-3.18.0.md
- content/releases/release-3.18.1.md
> fix: preview text for 3.18.0 and 3.18.1 releases

- antora-ui-camel/gulp.d/tasks/build.js
- antora-ui-camel/public/_/helpers/order_components.js
- antora-ui-camel/src/css/base.css
- antora-ui-camel/src/css/doc.css
- antora-ui-camel/src/css/fa-emulated.css
- antora-ui-camel/src/css/footer.css
- antora-ui-camel/src/css/header.css
- antora-ui-camel/src/css/pagination.css
- antora-ui-camel/src/css/site.css
- antora-ui-camel/src/css/toc.css
- antora-ui-camel/src/helpers/order_components.js
- antora-ui-camel/src/js/01-nav.js
- antora-ui-camel/src/js/vendor/algoliasearch.bundle.js
Seems this wasn't run in a while.
> chore: run `yarn format`

- content/community/articles.md
> add link for camel,sap example

- content/releases/kamelets/release-0.9.2.md
> Added Camel Kamelets release 0.9.2

- content/releases/kamelets/release-0.9.3.md
> Release Camel-Kamelets 0.9.3

- layouts/partials/header.html
> fix: og:image

- content/security/CVE-2022-45046.md
- content/security/CVE-2022-45046.txt.asc
> Added security advisory for CVE-2022-45046

- content/security/CVE-2022-45046.txt.asc
> CVE-2022-45046 mitigation fixed

- content/security/CVE-2022-45046.md
- content/security/CVE-2022-45046.txt.asc
> Retracting CVE-2022-45046

- content/releases/ckc/release-3.19.0.md
Camel Kafka Connector 3.19.0 release notes.
> Created release-3.19.0.md

- content/community/user-stories.md
- Fix user stories formatting.
> Fix user stories formatting.

- content/releases/kamelets/release-3.20.1.md
> Added Camel Kamelets release 3.20.1

- content/releases/kamelets/release-3.20.1.1.md
> Released Camel Kamelets 3.20.1.1

- content/blog/2023/03/camel-k-telemetry/index.md
Applied minor improvements to the recently published [distributed tracing blog post](https://camel.apache.org/blog/2023/03/camel-k-telemetry/).
cc @gansheer
> Minor improvements distributed tracing blog

- content/community/team.md
I have contributed into the Apache Camel project and want to add my name into contributors table.
Merged pull request: https://github.com/apache/camel/pull/7019
> Add stn1slv to contributors table

- content/blog/2023/02/camel-k-release-1-12/index.md
Add missing tracing feature change in camel-k 1.12 release announce blog post
> Add missing tracing feature change in camel-k 1.12 release

- content/community/team.md
Added Marat Gubaidullin to the list of commiters
> Update list of committers

- layouts/partials/releases/version_sort.html
> fix: prioritize the weight of RC vs M releases

- content/blog/2023/08/camel4-whatsnew/index.md
@davsclaus This is what the tool suggested.
> Apply editing changes for grammar check tools

- content/blog/2023/11/vscode-camelk-release-0.0.36/index.md
> Release announcement VS Code Tooling for Camel K 0.0.36

- .github/workflows/main-push-ui-bundle.yml
- .github/workflows/pr.yaml
- .github/workflows/preview.yaml
Main motivation here is to get faster artifact uploads, which currently take up significant time of the workflow.
> chore: update GitHub actions

- README.md
documentation
Same as #1195 but rebased for the preview
> chore: Update minimal version for Node to 18 and recommend 20 in

- content/community/user-stories.md
- Removed outdated, archived and unmaintained projects and products
- Added a few projects using Camel
> Updated user stories

- content/releases/upgrade-recipes/release-4.8.0.md
- data/release-categories.yaml
- layouts/partials/releases/camel-upgrade-recipes.html
> Added Website section for Camel-upgrade-recipes in download and release

- content/blog/2023/07/camel-k-gitops/index.md
Closes https://github.com/squakez/camelk-gitops-example/issues/1
> fix(blog): note with certain version not supported

- content/releases/k/release-2.5.1.md
- content/releases/k/release-2.6.0.md
Hi there. I just noticed the dates on the releases page is wrong. I just changed the year of the releases to 2025.
> Fixing dates on release page of Camel-K

- content/blog/2025/10/camel415-whatsnew/index.md
Add details on langchain4j-embeddingstore component and the undertow metrics in the actuator endpoint.
> Add details on langchain4j-embeddingstore component and the undertow metrics in the actuator endpoint.
